#!/bin/bash

# Variabile
OS=`cat /etc/os-release | grep -w "NAME" | awk -F"=" '{print $2}' | tr -d \"` # Extract the OS Model
LOG_DIR="/tmp"                                                                # LogFile for the output
LOG_NAME=$1                                                                   # Log Name
LOG_LOCATION="$LOG_DIR/$LOG_NAME.log"          
# Location
# Main

# check param
if [ $# == 0 ]
then
  echo "ERROR - You must run this script with a parameter!"
  echo "./install_mysql.sh [LOG_NAME]"
  echo "Example: ./install_mysql.sh "
  exit 3
fi

# If the log folder does not exist -> We create it 
if [ ! -d $LOG_DIR ]
then
  mkdir -p $LOG_DIR
fi

# Check OS
echo "The OS system is: $OS" >> $LOG_LOCATION

# Installer
if [[ $OS == "Ubuntu" ]]
then
  # Install MySQL
  sudo apt install mysql-server >> $LOG_LOCATION

  # Verif Status
  STATUS=`service mysql status | grep Active | awk '{print $2}'`
  echo "====== MY STATUS IS: $STATUS =======" >> $LOG_LOCATION
  if [ $STATUS == "inactive" ]
  then
    sudo service mysql start >> $LOG_LOCATION
    service mysql status >> $LOG_LOCATION
    echo "===== MYSQL Service Started on $OS ====" >> $LOG_LOCATION
  fi
elif [[ $OS == "CentOS Stream" ]]
then
  # Install MySQL
  sudo yum update -y
  sudo wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm >> $LOG_LOCATION
  sudo rpm -Uvh mysql80-community-release-el7-3.noarch.rpm  >> $LOG_LOCATION
  sudo yum install -y mysql-server >> $LOG_LOCATION

  # Status
  STATUS=`service mysqld status | grep Active | awk '{print $2}'`
  echo "====== MY STATUS IS: $STATUS =======" >> $LOG_LOCATION
  if [ $STATUS == "inactive" ]
  then
    sudo service mysqld start >> $LOG_LOCATION
    service mysqld status >> $LOG_LOCATION
    echo "===== MYSQL Service Started on $OS ====" >> $LOG_LOCATION
  fi
else
  echo "The OS is NOT UBUNTU OR CENTOS!" >> $LOG_LOCATION
fi
